### ISSUE TITLE
Assignment 2 tag?

### ISSUE THREAD

**Issue by patilav** [mukulbichkar19/WebDevSpring2016#2]
I have notified you earlier to follow the assignment tagging instructions.
Kindly reply with the tag which belongs to Client side development and all assignments after that.
Send me and email at patil.av@husky.neu.edu with a proper tag.
Your assignment will be graded after I get that information.

**Comment by mukulbichkar19** [comment]
Hello,
I have checked the instructions present on the portal and it says the following:-
"When you are ready to submit this assignment, tag your last commit you wish to be graded on as a assignment1. You can keep working and committing and pushing. The TAs and instructors can always view your assignment using the assignment1 tag."
So that's what I did for assignment 1, which you said was wrong. I asked you what was wrong, too which I did not get a specific reply as to what was wrong. I know you guys have a lot of assignments to grade, but please if you can specify as to what is wrong we can rectify it.
So, the next time I changed the 'a' to a 'A' in Assignment2. I am sorry for the trouble but if you can give me specific direction than general ones it would be better as I will know what to fix.
Thanks,
Mukul.

**Comment by patilav** [comment]
What you have done is versioning. 1.0.0 
Everyone has asked to follow the tagging method as assignment2, assignment3

These instructions exists in the problem description since the beginning 
** http://portal-cs5610online.rhcloud.com/portal/index.html#/modules/2/assignments **

**Do all your work in a directory called assignment off of the public directory of your OpenShift Web application project. Commit your work frequently throughout the day and push your changes at the end of the day to deploy and restart your OpenShift server. When you are ready to submit this assignment, tag your last commit you wish to be graded on as a assignment1. You can keep working and committing and pushing. The TAs and instructors can always view your assignment using the assignment1 tag.**

What I am expecting from you right now is to just tell me which revision number from your code has all the data for assignment2 and assignment3 to avoid the confusion.

**Comment by mukulbichkar19** [comment]
Ok, I got what you are saying. It makes sense. I was confused because while releasing it, it asks for a tag version so I gave a  number to it. From here on, I will take care of entering it as assignment(i) for (i)th assignment. Also, following are my versions for assignment 2 and assignment 3,
|  Version        |     Assignment
|   2.0.0           |     assignment2
|   3.0.0           |     assignment3
Also, you can find the corresponding releases in the Release Tab wherein I have named it as Assignment2 and Assignment3 along with its corresponding 2.0.0 and 3.0.0 tags.

Thanks,
Mukul.
